import {Link} from "react-router-dom";import SectionHeading from "../components/SectionHeading";import ServiceCard from "../components/ServiceCard";import PriceCard from "../components/PriceCard";import CTA from "../components/CTA";import {services} from "../data/services";import {pricing} from "../data/pricing";
const visualCards=[
{cls:"cyan",src:"/assets/cmyk-large-format.svg",label:"CMYK",sub:"FULL COLOUR"},
{cls:"magenta",src:"/assets/large-format-printer.svg",label:"PRINT",sub:"LARGE FORMAT"},
{cls:"yellow",src:"/assets/uv-printer.svg",label:"BIG",sub:"HIGH IMPACT"},
{cls:"black",src:"/assets/vinyl-printer.svg",label:"BRAND",sub:"MADE TO STAND OUT"}
];
export default function Home(){return <><section className="hero"><div className="hero-shape s1"/><div className="hero-shape s2"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow pill">PRINT • BRAND • WEAR</span><h1>Your vision,<br/><span>printed perfectly.</span></h1><p>From business cards to bold banners, branded apparel and complete signage — TENDIA PRINTING turns your ideas into colour, scale and impact.</p><div className="hero-actions"><Link className="primary-btn" to="/contact#quote">Get a Free Quote ↗</Link><Link className="outline-btn" to="/services">Explore Services</Link></div><div className="trust-row"><b>📍 Randfontein</b><b>💬 075 443 9922</b><b>⚡ Quality focused</b></div></div><div className="hero-visual" aria-label="Large format printing visuals"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/>{visualCards.map((v,i)=><div className={"print-card "+v.cls} key={v.label}><img src={v.src} alt={v.sub}/><div className="print-card-overlay"><strong>{v.label}</strong><small>{v.sub}</small></div></div>)}<div className="hero-sticker"><span>CMYK</span><small>PRINT<br/>ENERGY</small></div></div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="WHAT WE DO" title={<>Print it. Brand it.<br/><span>Make it memorable.</span></>} text="A complete printing partner for businesses, events, creators and everyday customers."/><div className="service-grid">{services.map((s,i)=><ServiceCard service={s} index={i} key={s.id}/>)}</div></div></section>
<section className="price-preview"><div className="container"><SectionHeading eyebrow="POPULAR PRICES" title="Straightforward starting prices." text="Need something custom? Send us your artwork, size and quantity for a tailored quote."/><div className="price-grid">{pricing.slice(0,6).map((p,i)=><PriceCard item={p} index={i} key={p.title}/>)}</div><Link className="outline-btn centered" to="/pricing">View full pricing →</Link></div></section>
<section className="why"><div className="container why-grid"><div><SectionHeading eyebrow="WHY TENDIA" title={<>Good printing is more than ink on paper.</>} text="We focus on clean production, strong colour, useful advice and a finished result you are proud to put in front of customers."/></div><div className="stats"><div><strong>01</strong><span>Quality-first production</span></div><div><strong>02</strong><span>Friendly, practical service</span></div><div><strong>03</strong><span>Digital + large format + apparel</span></div><div><strong>04</strong><span>Built around your brand</span></div></div></div></section><CTA/></>}